sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: '8'
branches:
  only:
    - master
notifications:
  email: false
script:
  - npm run validate
before_script:
  - npm prune
after_success:
  - npm run report-coverage
  - npm run semantic-release
